### PR TITLE
Review these.

### PR DESCRIPTION
**Pull request by 7ranceaddic7**
I think we got crossed at some point.

### CODE REVIEW

**Comment by 7ranceaddic7** [comment]
No conflicts.

**Comment by Lisias** [comment]
I swear I had fixed that... o.O

I will check the git's history and come back in a minute...

**Comment by Lisias** [comment]
It's fixed on the dev branch

https://github.com/net-lisias-ksp/TweakScaleCompanion_FS/blob/dev/GameData/TweakScaleCompanion/FS/patches/000_CleanUp.cfg

And by the very you of you :P (the good part of being non native English is that we can made up things and walk away from it):

https://github.com/net-lisias-ksp/TweakScaleCompanion_FS/commit/1a42cf16c758bbb953ab6dc1f22d11191758e53c#diff-a35d26747997fccd7326de337511e8ea

I will check now why in hell I let your fix behind in the newest release....

**Comment by Lisias** [comment]
Hum... I'm innocent. This time.

The good line is there on my master: https://github.com/net-lisias-ksp/TweakScaleCompanion_FS/blob/405ceea16c253c1aac6ad741a4d4d73d597dc5e8/GameData/TweakScaleCompanion/FS/patches/000_CleanUp.cfg#L28

Since this is already applied on my repo, I'm closing this.

I don't have an explanation for the happening. I'm sorry this wasted your time.

**Pull request closed without merging**
